# This is a basic workflow to help you get started with Actions

name: RSS_READER_CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  testing:
    
     runs-on: ubuntu-latest
     
     steps:
       # Run linter
       - name: Run linter
         run: npx eslint .

       # Run test
       - name: Run tests
         run: npm test

